.PHONY: clean

run_test: 
	python3 network_test.py

run_parser:
	python3 parser.py

# eu levei uma hora de pesquisas intensas no SO só pra chegar nesta maldita solução de uma misera linha que funciona lindamente bem
clean:
	cd ./Outputs; find . -name "*.txt" -type f -delete
# parse:

